---
# tasks file for gitlab_runner

- name: include assert.yml
  include_tasks: assert.yml
  run_once: yes

- name: install requirements
  package:
    name: "{{ gitlab_runner_requirements }}"
    state: present

- name: get repository installation script
  get_url:
    url: "https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.{{ gitlab_runner_package_type }}.sh"
    dest: /tmp/gitlab-runner-script.sh
    mode: "750"

- name: run repository installation script
  command: /tmp/gitlab-runner-script.sh
  args:
    creates: "{{ gitlab_runner_repository_file }}"

- name: install gitlab-runner
  package:
    name: gitlab-runner
    state: present

- name: get registration status
  command: gitlab-runner list
  register: gitlab_runner_get_registration_status
  changed_when: no

- name: register gitlab runner
  command: >
    gitlab-runner register --non-interactive
    --url "{{ gitlab_runner_url }}"
    --registration-token "{{ gitlab_runner_token }}"
    --description "{{ gitlab_runner_description }}"
    --tag-list "{{ gitlab_runner_tags }}"
    --executor "{{ gitlab_runner_executor }}"
    --docker-image "{{ gitlab_runner_docker_image }}"
  when:
    - "'{{ gitlab_runner_description }}' not in gitlab_runner_get_registration_status.stdout"

# TODO: Remove clutter stuff.
# - name: make sure /etc/systemd/system/gitlab-runner.service.d exists
#   file:
#     path: /etc/systemd/system/gitlab-runner.service.d
#     state: directory
#     mode: "0750"
#
# - name: set specific startup configurations
#   template:
#     src: exec_start.conf.j2
#     dest: /etc/systemd/system/gitlab-runner.service.d/exec_start.conf
#     mode: "0640"
#   notify:
#     - reload systemd
#     - restart gitlab-runner

- name: start and enable gitlab-runner
  service:
    name: gitlab-runner
    state: started
    enabled: yes
