---
# tasks file for gitlab_runner
- name: install requirements
  package:
    name: "{{ gitlab_runner_requirements }}"
    state: present
  register: gitlab_runner_install_requirements
  until: gitlab_runner_install_requirements is succeeded
  retries: 3

- name: get repository installation script
  get_url:
    url: "https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.{{ gitlab_runner_package_type }}.sh"
    dest: /tmp/gitlab-runner-script.sh
    mode: 0750

- name: run repository installation script
  command: /tmp/gitlab-runner-script.sh
  args:
    creates: "{{ gitlab_runner_repository_file }}"

- name: install gitlab-runner
  package:
    name: gitlab-runner
    state: present
  register: gitlab_runner_install_gitlab_runner
  until: gitlab_runner_install_gitlab_runner is succeeded
  retries: 3
  notify:
    - register gitlab runner

- name: make sure /etc/systemd/system/gitlab-runner.service.d exists
  file:
    path: /etc/systemd/system/gitlab-runner.service.d
    state: directory
    recurse: yes

- name: set specific startup configurations
  template:
    src: exec_start.conf.j2
    dest: /etc/systemd/system/gitlab-runner.service.d/exec_start.conf
  notify:
    - restart gitlab-runner

- name: start and enable gitlab-runner
  service:
    name: gitlab-runner
    state: started
    enabled: yes
  when:
    - ansible_virtualization_type != "docker"
